<?php
/**
 * @file
 * Contains module asset_injector.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function asset_injector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.asset_injector':
      $output = '<p>' . t('Use Asset injector rules to add small snippets of code to the page output when specific criteria are met. For example, a simple rule could float a particular div to the right on node editing pages.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_asset_injector_asset_info().
 */
function asset_injector_asset_injector_asset_info() {
  return array(
    'css_injector',
    'js_injector',
  );
}

/**
 * Implements hook_library_info_build().
 */
function asset_injector_library_info_build() {
  $libraries = [];
  foreach (asset_injector_get_assets() as $asset) {
    $libraries = array_merge($libraries, $asset->getLibrary());
  }
  \Drupal::moduleHandler()
    ->alter('asset_injector_library_info_build', $libraries);
  return $libraries;
}

/**
 * Implements hook_page_attachments().
 */
function asset_injector_page_attachments(array &$attachments) {
  foreach (asset_injector_get_assets() as $asset) {
    if ($asset->isActive() && ($file = $asset->getFile())) {
      $asset->createFile();
      $attachments['#attached']['library'][] = $asset->getAttachment();
    }
  }
}

/**
 * Get all available assets.
 *
 * @return array
 *   Assets from css & js injectors.
 */
function asset_injector_get_assets() {
  $entities = \Drupal::ModuleHandler()->invokeAll('asset_injector_asset_info');
  $assets = [];
  foreach ($entities as $entity_type) {
    $class = Drupal::entityTypeManager()
      ->getDefinition($entity_type)
      ->getClass();
    $rule_ids = Drupal::entityQuery($entity_type)->execute();
    foreach ($class::loadMultiple($rule_ids) as $rule) {
      $assets[] = $rule;
    }
  }
  return $assets;
}
